# Please be aware that I am still a noob at workflows, pull requests & fixes to it are welcome :)
name: CI-CD 

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 6 * * *  # Daily 6AM UTC build


jobs:
  test:
    permissions:
      contents: read # to fetch code (actions/checkout) (I'll implement add package uploading later)

    strategy:
      matrix:
        pyver: ['3.9', '3.10', '3.11', '3.12', '3.13']
        no-extensions: ['', 'Y']
        os: [ubuntu, macos, windows]
        experimental: [false]
        exclude:
          - os: macos
            no-extensions: 'Y'
          - os: windows
            no-extensions: 'Y'
          # Not ready to add custom thingies yet...
          - os: ubuntu
            no-extensions: 'Y'
        # This is on my todolist Skipping over for now while I test the others - Vizonex
        # include:
        #   - pyver: pypy-3.9
        #     no-extensions: 'Y'
        #     os: ubuntu
        #     experimental: false
        #   - os: ubuntu
        #     pyver: "3.14"
        #     experimental: true
        #     no-extensions: 'Y'
      fail-fast: true
    
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Setup Python ${{ matrix.pyver }}
      id: python-install
      uses: actions/setup-python@v5
      with:
        allow-prereleases: true
        python-version: ${{ matrix.pyver }}
    
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Cache PyPI
      uses: actions/cache@v4.2.3
      with:
        key: pip-ci-${{ runner.os }}-${{ matrix.pyver }}-${{ matrix.no-extensions }}-${{ hashFiles('requirements/*.txt') }}
        path: ${{ steps.pip-cache.outputs.dir }}
        restore-keys: |
            pip-ci-${{ runner.os }}-${{ matrix.pyver }}-${{ matrix.no-extensions }}-

    # NOTE: We need to install cython in order to compile all
    # of these since cyares is a cython library.
    # I'll see about merging files the same way winloop does in a future update.
    # I also am thinking about adding in a CPython Capsule for those intrested in having a C-API :)
    - name: Update pip, wheel, setuptools, build, twine, cython
      run: |
        python -m pip install -U pip wheel setuptools build twine cython 
    - name: Install dependencies
      run: |
        python -m pip install -r requirements/test.txt

    - name: Install self
      run: python -m pip install -e .

    - name: Run PyTests
      env:
        COLOR: yes
        PIP_USER: 1
      run: pytest
      shell: bash
    
